# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from hotel_rooms.bookings.grpc import bookings_pb2 as hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2


class BookingControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/hotel_rooms.bookings.BookingController/Create',
                request_serializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingRequest.SerializeToString,
                response_deserializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/hotel_rooms.bookings.BookingController/Destroy',
                request_serializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.List = channel.unary_unary(
                '/hotel_rooms.bookings.BookingController/List',
                request_serializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingListRequest.SerializeToString,
                response_deserializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingListResponse.FromString,
                )
        self.PartialUpdate = channel.unary_unary(
                '/hotel_rooms.bookings.BookingController/PartialUpdate',
                request_serializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingPartialUpdateRequest.SerializeToString,
                response_deserializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/hotel_rooms.bookings.BookingController/Retrieve',
                request_serializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingRetrieveRequest.SerializeToString,
                response_deserializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/hotel_rooms.bookings.BookingController/Update',
                request_serializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingRequest.SerializeToString,
                response_deserializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingResponse.FromString,
                )


class BookingControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingRequest.FromString,
                    response_serializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingListRequest.FromString,
                    response_serializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingPartialUpdateRequest.FromString,
                    response_serializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingRetrieveRequest.FromString,
                    response_serializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingRequest.FromString,
                    response_serializer=hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hotel_rooms.bookings.BookingController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookingController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms.bookings.BookingController/Create',
            hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingRequest.SerializeToString,
            hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms.bookings.BookingController/Destroy',
            hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms.bookings.BookingController/List',
            hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingListRequest.SerializeToString,
            hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms.bookings.BookingController/PartialUpdate',
            hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingPartialUpdateRequest.SerializeToString,
            hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms.bookings.BookingController/Retrieve',
            hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingRetrieveRequest.SerializeToString,
            hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms.bookings.BookingController/Update',
            hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingRequest.SerializeToString,
            hotel__rooms_dot_bookings_dot_grpc_dot_bookings__pb2.BookingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
