# Generated by Django 5.0.3 on 2024-04-10 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment_id",
            field=models.PositiveBigIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Payment ID",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user_id",
            field=models.PositiveBigIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="User ID",
            ),
        ),
    ]
