# Generated by Django 5.0.3 on 2024-04-11 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_payment_id_alter_booking_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="payment_id",
        ),
    ]
