# Generated by Django 5.0.3 on 2024-04-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False, verbose_name='Available')),
                ('n_of_beds', models.PositiveSmallIntegerField(verbose_name='Number of beds')),
                ('numeration', models.PositiveSmallIntegerField(verbose_name='Room numeration')),
                ('n_of_bathrooms', models.PositiveSmallIntegerField(verbose_name='Number of bathrooms')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
