# Generated by Django 5.0.3 on 2024-04-05 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="n_of_bathrooms",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Number of bathrooms",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="n_of_beds",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Number of beds",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="numeration",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Room numeration",
            ),
        ),
    ]
