# Generated by Django 5.0.3 on 2024-04-05 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_room_n_of_bathrooms_alter_room_n_of_beds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="numeration",
            field=models.PositiveSmallIntegerField(
                unique=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Room numeration",
            ),
        ),
    ]
