# Generated by Django 5.0.3 on 2024-04-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_numeration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
    ]
