# Generated by Django 5.0.3 on 2024-04-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.BooleanField(blank=True, default=True, verbose_name='Available'),
        ),
    ]
