# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from hotel_rooms.rooms.grpc import rooms_pb2 as hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2


class RoomControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/hotel_rooms.rooms.RoomController/Create',
                request_serializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomRequest.SerializeToString,
                response_deserializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/hotel_rooms.rooms.RoomController/Destroy',
                request_serializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.List = channel.unary_unary(
                '/hotel_rooms.rooms.RoomController/List',
                request_serializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomListRequest.SerializeToString,
                response_deserializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomListResponse.FromString,
                )
        self.PartialUpdate = channel.unary_unary(
                '/hotel_rooms.rooms.RoomController/PartialUpdate',
                request_serializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomPartialUpdateRequest.SerializeToString,
                response_deserializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/hotel_rooms.rooms.RoomController/Retrieve',
                request_serializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomRetrieveRequest.SerializeToString,
                response_deserializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/hotel_rooms.rooms.RoomController/Update',
                request_serializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomRequest.SerializeToString,
                response_deserializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomResponse.FromString,
                )


class RoomControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoomControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomRequest.FromString,
                    response_serializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomListRequest.FromString,
                    response_serializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomPartialUpdateRequest.FromString,
                    response_serializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomRetrieveRequest.FromString,
                    response_serializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomRequest.FromString,
                    response_serializer=hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hotel_rooms.rooms.RoomController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RoomController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms.rooms.RoomController/Create',
            hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomRequest.SerializeToString,
            hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms.rooms.RoomController/Destroy',
            hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms.rooms.RoomController/List',
            hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomListRequest.SerializeToString,
            hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms.rooms.RoomController/PartialUpdate',
            hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomPartialUpdateRequest.SerializeToString,
            hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms.rooms.RoomController/Retrieve',
            hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomRetrieveRequest.SerializeToString,
            hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms.rooms.RoomController/Update',
            hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomRequest.SerializeToString,
            hotel__rooms_dot_rooms_dot_grpc_dot_rooms__pb2.RoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
