# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hotel_rooms/rooms/grpc/rooms.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"hotel_rooms/rooms/grpc/rooms.proto\x12\x11hotel_rooms.rooms\x1a\x1bgoogle/protobuf/empty.proto\" \n\x12RoomDestroyRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x11\n\x0fRoomListRequest\"S\n\x10RoomListResponse\x12\x30\n\x07results\x18\x01 \x03(\x0b\x32\x1f.hotel_rooms.rooms.RoomResponse\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"\x98\x01\n\x18RoomPartialUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tavailable\x18\x02 \x01(\x08\x12\x11\n\tn_of_beds\x18\x03 \x01(\x05\x12\x12\n\nnumeration\x18\x04 \x01(\x05\x12\x16\n\x0en_of_bathrooms\x18\x05 \x01(\x05\x12\x1e\n\x16_partial_update_fields\x18\x06 \x03(\t\"k\n\x0bRoomRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tavailable\x18\x02 \x01(\x08\x12\x11\n\tn_of_beds\x18\x03 \x01(\x05\x12\x12\n\nnumeration\x18\x04 \x01(\x05\x12\x16\n\x0en_of_bathrooms\x18\x05 \x01(\x05\"l\n\x0cRoomResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tavailable\x18\x02 \x01(\x08\x12\x11\n\tn_of_beds\x18\x03 \x01(\x05\x12\x12\n\nnumeration\x18\x04 \x01(\x05\x12\x16\n\x0en_of_bathrooms\x18\x05 \x01(\x05\"!\n\x13RoomRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x81\x04\n\x0eRoomController\x12K\n\x06\x43reate\x12\x1e.hotel_rooms.rooms.RoomRequest\x1a\x1f.hotel_rooms.rooms.RoomResponse\"\x00\x12J\n\x07\x44\x65stroy\x12%.hotel_rooms.rooms.RoomDestroyRequest\x1a\x16.google.protobuf.Empty\"\x00\x12Q\n\x04List\x12\".hotel_rooms.rooms.RoomListRequest\x1a#.hotel_rooms.rooms.RoomListResponse\"\x00\x12_\n\rPartialUpdate\x12+.hotel_rooms.rooms.RoomPartialUpdateRequest\x1a\x1f.hotel_rooms.rooms.RoomResponse\"\x00\x12U\n\x08Retrieve\x12&.hotel_rooms.rooms.RoomRetrieveRequest\x1a\x1f.hotel_rooms.rooms.RoomResponse\"\x00\x12K\n\x06Update\x12\x1e.hotel_rooms.rooms.RoomRequest\x1a\x1f.hotel_rooms.rooms.RoomResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hotel_rooms.rooms.grpc.rooms_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROOMDESTROYREQUEST']._serialized_start=86
  _globals['_ROOMDESTROYREQUEST']._serialized_end=118
  _globals['_ROOMLISTREQUEST']._serialized_start=120
  _globals['_ROOMLISTREQUEST']._serialized_end=137
  _globals['_ROOMLISTRESPONSE']._serialized_start=139
  _globals['_ROOMLISTRESPONSE']._serialized_end=222
  _globals['_ROOMPARTIALUPDATEREQUEST']._serialized_start=225
  _globals['_ROOMPARTIALUPDATEREQUEST']._serialized_end=377
  _globals['_ROOMREQUEST']._serialized_start=379
  _globals['_ROOMREQUEST']._serialized_end=486
  _globals['_ROOMRESPONSE']._serialized_start=488
  _globals['_ROOMRESPONSE']._serialized_end=596
  _globals['_ROOMRETRIEVEREQUEST']._serialized_start=598
  _globals['_ROOMRETRIEVEREQUEST']._serialized_end=631
  _globals['_ROOMCONTROLLER']._serialized_start=634
  _globals['_ROOMCONTROLLER']._serialized_end=1147
# @@protoc_insertion_point(module_scope)
